"""init database

Revision ID: 2dc59609739f
Revises: 2e015fb813cf
Create Date: 2026-04-21 08:33:33.043499

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2dc59609739f'
down_revision = '2e015fb813cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_progress',
    sa.Column('course_progress_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('completed_lessons', sa.Integer(), nullable=True),
    sa.Column('total_lessons', sa.Integer(), nullable=True),
    sa.Column('progress_percent', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('not_started', 'completed', 'in_progress', name='course_status'), nullable=True),
    sa.Column('last_learned_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('course_progress_id'),
    sa.UniqueConstraint('student_id', 'course_id', name='unique_student_course')
    )
    op.create_table('reviews',
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('review_id'),
    sa.UniqueConstraint('course_id', 'user_id', name='unique_user_review')
    )
    op.create_table('lesson_progress',
    sa.Column('lesson_progress_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('completion_percent', sa.Float(), nullable=True),
    sa.Column('last_accessed_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.lesson_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('lesson_progress_id'),
    sa.UniqueConstraint('student_id', 'lesson_id', name='unique_student_lesson')
    )
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_520_ci', length=500),
               type_=sa.String(length=255),
               existing_nullable=True)

    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.drop_column('progress')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_520_ci', length=50),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_520_ci', length=50),
               nullable=True)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('progress', mysql.FLOAT(), nullable=True))

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_520_ci', length=500),
               existing_nullable=True)

    op.drop_table('lesson_progress')
    op.drop_table('reviews')
    op.drop_table('course_progress')
    # ### end Alembic commands ###
