"""init database

Revision ID: fa916f71b4c9
Revises: 2dc59609739f
Create Date: 2026-04-21 08:39:11.969409

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fa916f71b4c9'
down_revision = '2dc59609739f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider', sa.String(length=50), nullable=True))
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_520_ci', length=255),
               nullable=True)
        batch_op.alter_column('role',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_520_ci', length=50),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_520_ci', length=50),
               nullable=False)
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_520_ci', length=255),
               nullable=False)
        batch_op.drop_column('provider')

    # ### end Alembic commands ###
